<a href="https://colab.research.google.com/github/Abhilashvadukari/1227pythonds/blob/main/Asgnmnt02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

arr = np.random.randint(50, 100, size=(4,4))
print("Array:\n", arr)


print("\nRow-wise Mean:", np.mean(arr, axis=1))
print("Column-wise Mean:", np.mean(arr, axis=0))

print("\nRow-wise Median:", np.median(arr, axis=1))
print("Column-wise Median:", np.median(arr, axis=0))

print("\nRow-wise Std Dev:", np.std(arr, axis=1))
print("Column-wise Std Dev:", np.std(arr, axis=0))


global_max = arr.max()
global_min = arr.min()
max_idx = np.unravel_index(arr.argmax(), arr.shape)
min_idx = np.unravel_index(arr.argmin(), arr.shape)

print("\nGlobal Max:", global_max, "at index", max_idx)
print("Global Min:", global_min, "at index", min_idx)


Array:
 [[66 69 84 69]
 [58 70 90 73]
 [59 59 77 73]
 [71 86 89 64]]

Row-wise Mean: [72.   72.75 67.   77.5 ]
Column-wise Mean: [63.5  71.   85.   69.75]

Row-wise Median: [69.  71.5 66.  78.5]
Column-wise Median: [62.5 69.5 86.5 71. ]

Row-wise Std Dev: [ 7.03562364 11.43186337  8.1240384  10.35615759]
Column-wise Std Dev: [5.31507291 9.6695398  5.14781507 3.69966215]

Global Max: 90 at index (np.int64(1), np.int64(2))
Global Min: 58 at index (np.int64(1), np.int64(0))
