<a href="https://colab.research.google.com/github/Abhilashvadukari/1227pythonds/blob/main/Assgnmt02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


img = np.random.randint(0, 256, (3,3,3))
print("RGB Image Array:\n", img)


red, green, blue = img[:,:,0], img[:,:,1], img[:,:,2]
print("\nRed Channel:\n", red)
print("Green Channel:\n", green)
print("Blue Channel:\n", blue)

print("\nAverage Intensities - R:", red.mean(), "G:", green.mean(), "B:", blue.mean())

bright_img = np.clip(img + 50, 0, 255)
print("\nBrightened Image:\n", bright_img)


RGB Image Array:
 [[[173 155  81]
  [ 57  36 224]
  [ 20  50 236]]

 [[ 70  56 211]
  [ 68 192 224]
  [153 103 148]]

 [[165 216   7]
  [127  60  55]
  [224  18 101]]]

Red Channel:
 [[173  57  20]
 [ 70  68 153]
 [165 127 224]]
Green Channel:
 [[155  36  50]
 [ 56 192 103]
 [216  60  18]]
Blue Channel:
 [[ 81 224 236]
 [211 224 148]
 [  7  55 101]]

Average Intensities - R: 117.44444444444444 G: 98.44444444444444 B: 143.0

Brightened Image:
 [[[223 205 131]
  [107  86 255]
  [ 70 100 255]]

 [[120 106 255]
  [118 242 255]
  [203 153 198]]

 [[215 255  57]
  [177 110 105]
  [255  68 151]]]
