<a href="https://colab.research.google.com/github/Abhilashvadukari/1227pythonds/blob/main/lab04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr1=np.array([1,2,3,4,])
print(arr1)

[1 2 3 4]


In [ ]:
arr2=np.array([[1,2,3,4],[2,4,5,6]])
print(arr2)

[[1 2 3 4]
 [2 4 5 6]]


In [ ]:
a=np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
b=np.ones((2,2))
print("2X2\n",b)

2X2
 [[1. 1.]
 [1. 1.]]


In [ ]:
range=np.arange(0,10,2)
print(range)

[0 2 4 6 8]


In [ ]:
rd=np.random.rand(2,3)
print(rd)

[[0.21915919 0.92543047 0.0068124 ]
 [0.36473144 0.67270786 0.02961938]]


In [ ]:
arr=np.array([[1,2,3,4,],[2,3,4,5]])
print(arr.shape)
print(arr.ndim)
print(arr.dtype)
print(arr.size)
print(arr.itemsize)

(2, 4)
2
int64
8
8


In [ ]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr[1])
print(arr[1:5])
print(arr[1:5:2])
print(arr[-1])
print(arr[0:10:2])

2
[2 3 4 5]
[2 4]
10
[1 3 5 7 9]


In [ ]:
arr=np.array([[10,20,30,40],[20,30,40,50]])
print(arr[0][0])
print(arr[1][3])
print(arr[1::])
print(arr[::3])

10
50
[[20 30 40 50]]
[[10 20 30 40]]


In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [46]:
Brodcasting_example = np.array([[1, 2], [3, 4]], dtype=np.float64)
print("\nBroadcasting example:\n", Brodcasting_example)


Broadcasting example:
 [[1. 2.]
 [3. 4.]]
